version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-movies
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5438:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

